### ISSUE TITLE
3.0.6 release broken export

### ISSUE THREAD

**Issue by balthazar** [saltas888/react-router-query-middleware#1]
As stated, the module exports nothing since the latest version. Seems https://github.com/saltas888/react-router-query-middleware/commit/b059043641382abd8a1883296f3ac015ea0c75d4 is the impacting commit.

**Comment by saltas888** [comment]
Please use the latest version `3.1.0`. I think it is fixed as of https://github.com/saltas888/react-router-query-middleware/commit/55e820fed2b36998c70b89661e756bc53933488d. Let me know if it's ok

**Comment by balthazar** [comment]
Good now :)
